error chrome driver

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -50,7 +50,10 @@ jobs:
         run: |
           # Instalar Google Chrome
           sudo apt-get update
-          sudo apt-get install -y google-chrome-stable
+          sudo apt-get install -y google-chrome-stable || { echo 'Error al instalar Google Chrome'; exit 1; }
+
+          # Verificar que Google Chrome se haya instalado correctamente
+          google-chrome-stable --version || { echo 'Google Chrome no se pudo instalar correctamente'; exit 1; }
 
           # Obtener la versión de Google Chrome instalada
           CHROME_VERSION=$(google-chrome-stable --version | sed 's/[^0-9]*\([0-9]*\.[0-9]*\.[0-9]*\)\..*/\1/')
@@ -59,12 +62,16 @@ jobs:
           # Descargar la versión correspondiente de ChromeDriver
           CHROME_DRIVER_VERSION=$(curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION)
           echo "Versión de ChromeDriver: $CHROME_DRIVER_VERSION"
-          wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip
-          unzip chromedriver_linux64.zip
+          if [ -z "$CHROME_DRIVER_VERSION" ]; then
+            echo "No se pudo obtener la versión de ChromeDriver"; exit 1;
+          fi
+          
+          wget https://chromedriver.storage.googleapis.com/$CHROME_DRIVER_VERSION/chromedriver_linux64.zip || { echo 'Error al descargar ChromeDriver'; exit 1; }
+          unzip chromedriver_linux64.zip || { echo 'Error al descomprimir ChromeDriver'; exit 1; }
           sudo mv chromedriver /usr/local/bin/chromedriver
           sudo chmod +x /usr/local/bin/chromedriver
 
-          # Verificar versiones
+          # Verificar las versiones de Chrome y ChromeDriver
           google-chrome-stable --version
           chromedriver --version
 
